#-------------------------------
# Site Settings
title: Angel A. Valdenegro
logo: '../images/favicon.png'
description: Scientist, Communicator, and Tinkerer 
color_scheme: auto # You can choose three modes auto, light, and dark. By default, the auto mode is set, which means the user can choose the light or dark mode themself.


#-------------------------------
# Navigation Settings
menu__settings:
  menu__items:
    - title: 'Home'
      url: '/'
    - title: 'About'
      url: '/about/'
    - title: 'Work'
      url: '/work/'
    - title: 'Writing'
      url: '/blog/'
    - title: 'Pages'
      submenu:
      - url: '/contact/'
        title: 'Contact'


#-------------------------------
# Author Settings
author:
  author__name: Angel A. Valdenegro
  author__bio: I'm a lifelong learner with a passion for experimenting with and deploying new technologies. Originally trained with a physics background and then engaged in the aerospace, environmental, and data analytics industries.
  author__avatar: '../images/avatar.jpeg'

social:
- {icon: "ion-logo-twitter", link: "https://twitter.com/astroparticular"}
- {icon: "ion-logo-instagram", link: "https://instagram.com/angel.avz"}
- {icon: "ion-logo-github", link: "https://github.com/isoleph"}

# Example of adding a new link to the footer - {icon: "ion-logo-dribbble", link: "https://dribbble.com"}
# Other icons can be found at https://ionicons.com/v4/


#-------------------------------
# Hero Settings
hero:
  enable: true
  hero__title: Hi, I'm Angel Valdenegro.
  hero__description: I'm a lifelong learner with a passion for experimenting with and deploying new technologies. Originally trained with a physics background and then engaged in the aerospace, environmental, and data analytics industries.
  hero__image: "../images/joshua-tree.jpg"


# Newsletter
mailchimp:
  enable: true
  mailchimp__identifier: frnla.us6.list-manage.com/subscribe/post?u=6314d69a3f315af7ce3fb00a0&amp;id=3038727cc3 # Add your MailChimp form identifier. For example - frnla.us6.list-manage.com/subscribe/post?u=6314d69a3f315af7ce3fb00a0&amp;id=3038727cc3
  mailchimp__input__text: Your email address...
  mailchimp__button__text: Subscribe


#-------------------------------
# Work Settings
work:
  enable: true
  work__title: Work
  work__description: Feel free to take a look at my current or past projects.

#-------------------------------
# Blog Section
blog:
  enable: true

blog__settings:
  blog__title: Writing
  blog__description: Blog posts ranging from Physics concepts to other writings. For your convenience, you may search by tags. 


#-------------------------------
# Footer Settings
footer__background__image: "../images/bg.png"
footer__background__image__night: "../images/bg.png"

#-------------------------------
# Contact Settings
contact:
  email: valdenegro.angel@gmail.com # Add your form_id
  description: Akio comes with a built-in contact form, that you can use with Formspree service to handle up to 50 submissions per month for free. You could also easily switch to another contact form service if you want. # Add a description of your form

# NOTE
# Akio theme comes with a contact form built-in. You can use this form with Formspree (https://formspree.io/) service and get up to 50 submissions for free. Also, you can easily switch to another service if you want.


#-------------------------------
# Comment Section (Disqus)
disqus:
  enable: false
  disqus__identifier: anvod-studio-test # Add your shortname for Disqus Comment. For example anvod-studio-test


#-------------------------------
# Google Analytics
google-analytics: # Add your GA Tracking Id
